name: TestDriver.ai
description: AI QA Agent for GitHub
author: Dashcam.io
branding:
  icon: "user-check"
  color: "green"
inputs:
  prompt:
    description: >-
      The prompt to test. Example:
      1. Open Google Chrome
      2. Go to YouTube.com
      3. Search for "Rick Astley"
      4. Click on the first video
    required: true
  os:
    description: The operating system to use, mac or windows, will be windows by default
  prerun:
    description: >-
      A script to run before the test.
    required: false
  version:
    description: >-
      The TestDriver version to run. Default 1.0.0
    required: false
  key:
    description: >-
      Your Dashcam API key
    required: false
outputs:
  summary:
    description: >-
      The summary of the test result
  link:
    description: >-
      The share link of Dashcam.io recording
  markdown:
    description: >-
      A hotlinked image of the Dashcam.io recording
runs:
  using: node16
  main: ./dist/index.js
