name: Test PR
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  test-action:
    name: Test action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./
        with:
          version: v3.3.8
          prompt: |
            1. open youtube
            2. find a cat video
            3. quit the browser
            4. /summarize
          prerun: |
            npm install dashcam-chrome --save
            /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --load-extension=./node_modules/dashcam-chrome/build/ 1>/dev/null 2>&1 &
            exit
          key: ${{ secrets.DASHCAM_WORKSPACE_API }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_COLOR: "3"
