name: Test PR
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  test-action:
    name: Test action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./
        with:
          prompt: |
            1. open youtube.
            2. find a cat video
            3. quit the browser
        env:
          PERSONAL_GH_TOKEN: ${{ secrets.PERSONAL_GH_TOKEN }}
